name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.25.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}

    - name: Go version
      run: go version

    - name: build
      run: go build .